import type { Colaborador, Equipamento, Movimentacao } from '../types'

export const colaboradoresSeed: Omit<Colaborador, 'created_at'>[] = [
  { id: 1,  nome: 'Victor',       email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 2,  nome: 'Victoria',     email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 3,  nome: 'Ana Paula',    email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 4,  nome: 'Thamires RH',  email: null, setor: 'Administrativo', regime: 'Home office', status: 'Ativo' },
  { id: 5,  nome: 'Crislani',     email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 6,  nome: 'Monica',       email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 7,  nome: 'Dayana',       email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 8,  nome: 'Priscila',     email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 9,  nome: 'Ivani',        email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 10, nome: 'Duda',         email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 11, nome: 'Julia',        email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 12, nome: 'Iago',         email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 13, nome: 'Italo',        email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 14, nome: 'Patrícia',     email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 15, nome: 'Gabriella',    email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
  { id: 16, nome: 'Cecília',      email: null, setor: 'Home Office', regime: 'Home office', status: 'Ativo' },
]

export const equipamentosSeed: Omit<Equipamento, 'created_at' | 'colaborador'>[] = [
  { id: 'DF-001', descricao: 'All in One Positivo',   tipo: 'Computador', setor: 'Home Office', colaborador_id: 1,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-002', descricao: 'Kit Teclado e Mouse',   tipo: 'Periférico', setor: 'Home Office', colaborador_id: 1,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-003', descricao: 'All in One Positivo',   tipo: 'Computador', setor: 'Home Office', colaborador_id: 2,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-004', descricao: 'Monitor',               tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 2,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-005', descricao: 'All in One Arquimedes', tipo: 'Computador', setor: 'Home Office', colaborador_id: 3,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-006', descricao: 'Monitor LG',            tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 3,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-007', descricao: 'Teclado',               tipo: 'Teclado',    setor: 'Home Office', colaborador_id: 3,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-008', descricao: 'Mouse',                 tipo: 'Mouse',      setor: 'Home Office', colaborador_id: 3,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-009', descricao: 'Headset',               tipo: 'Headset',    setor: 'Home Office', colaborador_id: 3,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-010', descricao: 'Cadeira',               tipo: 'Outros',     setor: 'Home Office', colaborador_id: 3,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-011', descricao: 'Notebook Lenovo',       tipo: 'Notebook',   setor: 'Home Office', colaborador_id: 4,    status: 'Home office', alugado: false, valor: null, observacao: 'Transferido de Patrícia' },
  { id: 'DF-012', descricao: 'All in One Positivo',   tipo: 'Computador', setor: 'Home Office', colaborador_id: 5,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-013', descricao: 'Monitor',               tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 5,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-014', descricao: 'Notebook Lenovo',       tipo: 'Notebook',   setor: 'Home Office', colaborador_id: 6,    status: 'Home office', alugado: false, valor: null, observacao: 'Transferido de Thamires RH' },
  { id: 'DF-015', descricao: 'Monitor',               tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 6,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-016', descricao: 'All in One Lenovo',     tipo: 'Computador', setor: 'Home Office', colaborador_id: 7,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-017', descricao: 'All in One Arquimedes', tipo: 'Computador', setor: 'Home Office', colaborador_id: 8,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-018', descricao: 'Monitor',               tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 8,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-019', descricao: 'Kit Mouse e Teclado',   tipo: 'Periférico', setor: 'Home Office', colaborador_id: 8,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-020', descricao: 'Headset',               tipo: 'Headset',    setor: 'Home Office', colaborador_id: 8,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-021', descricao: 'All in One Arquimedes', tipo: 'Computador', setor: 'Home Office', colaborador_id: 9,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-022', descricao: 'Monitor',               tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 9,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-023', descricao: 'Kit Mouse e Teclado',   tipo: 'Periférico', setor: 'Home Office', colaborador_id: 9,    status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-024', descricao: 'All in One Positivo',   tipo: 'Computador', setor: 'Home Office', colaborador_id: 10,   status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-025', descricao: 'Monitor LG',            tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 10,   status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-026', descricao: 'Kit Mouse e Teclado',   tipo: 'Periférico', setor: 'Home Office', colaborador_id: 10,   status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-027', descricao: 'All in One Positivo',   tipo: 'Computador', setor: 'Home Office', colaborador_id: 11,   status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-028', descricao: 'Monitor LG',            tipo: 'Monitor',    setor: 'Home Office', colaborador_id: 11,   status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-029', descricao: 'Kit Mouse e Teclado',   tipo: 'Periférico', setor: 'Home Office', colaborador_id: 11,   status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-030', descricao: 'Notebook Lenovo',       tipo: 'Notebook',   setor: 'Home Office', colaborador_id: 12,   status: 'Home office', alugado: false, valor: null, observacao: null },
  { id: 'DF-031', descricao: 'Notebook Samsung',      tipo: 'Notebook',   setor: 'Home Office', colaborador_id: 13,   status: 'Home office', alugado: false, valor: null, observacao: 'Transferido de Cecília' },
  { id: 'DF-032', descricao: 'All in One Positivo',   tipo: 'Computador', setor: null,          colaborador_id: null, status: 'Pendente devolução', alugado: false, valor: null, observacao: 'Era de Gabriella, destino pendente' },
  { id: 'DF-033', descricao: 'Monitor',               tipo: 'Monitor',    setor: null,          colaborador_id: null, status: 'Pendente devolução', alugado: false, valor: null, observacao: 'Era de Gabriella, destino pendente' },
]

export const movimentacoesSeed: Omit<Movimentacao, 'id' | 'created_at' | 'equipamento' | 'colaborador'>[] = [
  { data: '2025-06-01', equipamento_id: 'DF-011', acao: 'Transferência de Patrícia para Thamires RH',  colaborador_id: 4,    responsavel: 'TI' },
  { data: '2025-06-05', equipamento_id: 'DF-014', acao: 'Transferência de Thamires RH para Monica',    colaborador_id: 6,    responsavel: 'TI' },
  { data: '2025-06-08', equipamento_id: 'DF-031', acao: 'Transferência de Cecília para Italo',         colaborador_id: 13,   responsavel: 'TI' },
  { data: '2025-06-10', equipamento_id: 'DF-032', acao: 'Devolução pendente — destino não confirmado', colaborador_id: null, responsavel: 'TI' },
  { data: '2025-06-10', equipamento_id: 'DF-033', acao: 'Devolução pendente — destino não confirmado', colaborador_id: null, responsavel: 'TI' },
]
